name: zds_flutter_example

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.1.0
  intl: ^0.18.0
  table_calendar: ^3.0.9
  zds_flutter:
    path: ../
  zeta_flutter: ^0.0.1+12

flutter:
  uses-material-design: true
